Repository PelagusWallet/pelagus-extension, pull requests merged in 2023-09, with the labels that each got.

#100 delete removeAddress functionality
  ui/components/AccountItem/AccountItemOptionsMenu.tsx
Labels: enhancement

#103 Changes message after onboarding
  ui/_locales/en/messages.json
Labels: bug

#96 Added connection error banner
  background/main.ts
  background/networks.ts
  background/redux-slices/ui.ts
  background/services/chain/index.ts
  background/services/chain/serial-fallback-provider.ts
  ui/components/Wallet/WalletNoConnectionBanner.tsx
  ui/pages/Wallet.tsx
Labels: ui-change
